apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: chronas-api-mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chronas-api-mongodb
    spec:
      containers:
      - name: chronas-api-mongodb
        image: mongo
        ports:
        - containerPort: 27017
          name: mongo:3.4.2
---
apiVersion: v1
kind: Service
metadata:
  name: chronas-api-mongodb
spec:
  ports:
  - port: 6379
  selector:
    app: chronas-api-mongodb
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: chronas-api-front
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chronas-api-front
    spec:
      containers:
      - name: chronas-api-front
        image: microsoft/azure-vote-front:redis-v1
        ports:
        - containerPort: 4040
        env:
        - name: MONGO_HOST
          value: mongodb://chronas-api-mongodb/chronas-api-development
---
apiVersion: v1
kind: Service
metadata:
  name: chronas-api-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
      targetPort: 4040
      protocol: TCP  
  selector:
    app: chronas-api-front