swagger: "2.0"

info:
  version: 0.1.0
  title: Chronas API
  description: This API provides authentication and CRUD operations for data used by the Chronas application. It is based on Node.js using ES6 and Express with Code Coverage and JWT Authentication. It implies an underlying MongoDB.

schemes:
  - http
host: api-dev.chronas.org
basePath: /v1

paths:
  /metadata:
    get:
      summary: Gets some metadata
      description: Get list of metadata keys.
      parameters:
       - name: f
         in: query
         description: comma sepperated list of filter
         type: array
         collectionFormat: csv
       - name: type
         in: query
         description: type
         type: string
       - name: subtype
         in: query
         description: subtype
         type: string
       - name: year
         in: query
         description: year YYYY ?
         type: integer
       - name: delta
         in: query
         description: delta
         type: integer         
      responses:
        200:
          description: A list of Metadata keys
          schema:
            type: array
            items:
              properties:
                _id:
                  type: string
                data:
                  type: string
                type:
                  type: string