apiVersion: v1
kind: Service
metadata:
  name: chronas-api
spec:
  ports:
  - port: 80
  selector:
    app: chronas-api
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chronas-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod  
spec:  
  tls:
  - hosts:
    - api.chronas.org
    secretName: api-crt
  rules:
  - host: api.chronas.org
    http:
      paths:
      - path: /
        backend:
          serviceName: chronas-api
          servicePort: 80    