apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: chronas-api
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: chronas-api
    spec:
      containers:
      - name: chronas-api
        image: aumanjoa/chronas-api:#{buildId}#
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /v1/health
            port: 80
          initialDelaySeconds: 55
          timeoutSeconds: 1
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /v1/health
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 15  
        env:
        - name: MONGO_HOST
          valueFrom:
            secretKeyRef:
              name: chronas-secrets
              key: MONGO_HOST
        - name: CHRONAS_HOST
          valueFrom:
            secretKeyRef:
              name: chronas-secrets
              key: CHRONAS_HOST              
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: chronas-secrets
              key: JWT_SECRET
        - name: CLOUDINARY_URL
          valueFrom:
            secretKeyRef:
              name: chronas-secrets
              key: CLOUDINARY_URL
        - name: FACEBOOK_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: chronas-secrets
              key: FACEBOOK_CLIENT_ID
        - name: FACEBOOK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: chronas-secrets
              key: FACEBOOK_CLIENT_SECRET
        - name: FACEBOOK_CALLBACK_URL
          valueFrom:
            secretKeyRef:
              name: chronas-secrets
              key: FACEBOOK_CALLBACK_URL
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: chronas-secrets
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: chronas-secrets
              key: GOOGLE_CLIENT_SECRET
        - name: GOOGLE_CALLBACK_URL
          valueFrom:
            secretKeyRef:
              name: chronas-secrets
              key: GOOGLE_CALLBACK_URL
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: chronas-secrets
              key: GITHUB_CLIENT_ID
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: chronas-secrets
              key: GITHUB_CLIENT_SECRET
        - name: GITHUB_CALLBACK_URL
          valueFrom:
            secretKeyRef:
              name: chronas-secrets
              key: GITHUB_CALLBACK_URL
        - name: TWITTER_CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              name: chronas-secrets
              key: TWITTER_CONSUMER_KEY
        - name: TWITTER_CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              name: chronas-secrets
              key: TWITTER_CONSUMER_SECRET
        - name: TWITTER_CALLBACK_URL
          valueFrom:
            secretKeyRef:
              name: chronas-secrets
              key: TWITTER_CALLBACK_URL
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          valueFrom:
            secretKeyRef:
              name: chronas-secrets
              key: APPINSIGHTS_INSTRUMENTATIONKEY          