apiVersion: v1
kind: Service
metadata:
  name: chronas-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: chronas-api
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chronas-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod  
spec:  
  tls:
  - hosts:
    - api-dev.chronas.org
    secretName: https-api-crt
  rules:
  - host: api-dev.chronas.org
    http:
      paths:
      - path: /
        backend:
          serviceName: chronas-api
          servicePort: 80    
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: https-api-crt
spec:
  secretName: https-api-crt
  dnsNames:
  - api-dev.chronas.org
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - api-dev.chronas.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer          