apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: chronas-api-mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chronas-api-mongodb
    spec:
      containers:
      - name: chronas-api-mongodb
        image: mongo
        ports:
        - containerPort: 27017
          hostPort: 27017