---
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    role: mongo-backup
  name: mgob-gstore-config
data:
  test.yml: |
    target:
      host: "mongo-0.mongo,mongo-1.mongo"
      port: 27017
      database: "chronas-api"
    scheduler:
      cron: "0 6 */1 * *"
      retention: 4
      timeout: 60
    azure:
      containerName: "backup"
      connectionString: "DefaultEndpointsProtocol=https;AccountName=backupchronas;AccountKey=bZsN0MWv0T2iQRPhGs/L3XRgD8w4lQgyiSX1BuqeY8s1p5gtZYKaD+H2AiBfN0SyVM/pTZY0i+INZPn2RuCAMw==;EndpointSuffix=core.windows.net"